import os
import requests
import uvicorn
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import Response
from fpdf import FPDF
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

app = FastAPI(title="Gemini Funding Proposal Generator")

API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    raise ValueError("GEMINI_API_KEY is missing in environment variables")

# --- IMPROVED PDF CLASS ---
class ProposalPDF(FPDF):
    def header(self):
        # Add a logo or company name here if you wanted
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100) # Gray color
        self.cell(0, 10, "Generated by AI Funding Assistant", align="R")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_pdf_from_text(text_content: str) -> bytes:
    pdf = ProposalPDF()
    pdf.add_page()
    
    # 1. Main Title
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 20, "Project Funding Proposal", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10) # Add space after title

    # 2. Configure Markdown Rendering
    # fpdf2 supports basic markdown: **bold**, __italics__, --strikethrough--
    pdf.set_font("Times", size=12) # Serif font looks more professional for documents
    
    # We sanitize the text to replace unsupported Unicode characters
    # Windows-1252 (latin-1) is the standard encoding for basic FPDF
    safe_text = text_content.encode('latin-1', 'replace').decode('latin-1')
    
    # Render the content with Markdown enabled
    # 'markdown=True' will render **bold** and *italics* correctly
    pdf.multi_cell(0, 8, text=safe_text, markdown=True)
    
    return pdf.output()

# --- DYNAMIC MODEL FINDER (Kept from previous success) ---
def find_best_model():
    list_url = f"https://generativelanguage.googleapis.com/v1beta/models?key={API_KEY}"
    try:
        response = requests.get(list_url, timeout=10)
        if response.status_code != 200: return None
        data = response.json()
        usable_models = [m['name'] for m in data.get('models', []) if 'generateContent' in m.get('supportedGenerationMethods', [])]
        
        # Priority: Flash -> Pro
        for m in usable_models: 
            if "flash" in m: return m
        for m in usable_models: 
            if "1.5-pro" in m: return m
        return usable_models[0] if usable_models else None
    except:
        return None

# --- API ENDPOINT ---
@app.post("/generate-proposal/")
def generate_proposal(report_text: str = None, file: UploadFile = File(None)):
    
    # 1. Extract Content
    content = ""
    try:
        if file:
            content_bytes = file.file.read()
            content = content_bytes.decode("utf-8")
        elif report_text:
            content = report_text
        else:
            raise HTTPException(status_code=400, detail="Please provide report_text or upload a file.")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Error reading file: {str(e)}")

    # 2. Construct Prompt for Better Formatting
    # We explicitly tell Gemini to use formatting that FPDF understands
    prompt = f"""
    You are a professional grant writer. 
    Rewrite the following feasibility report into a formal Funding Proposal.

    FORMATTING RULES FOR PDF GENERATION:
    1. Use Markdown for styling.
    2. Use **bold** for Section Headers (e.g. **1. EXECUTIVE SUMMARY**).
    3. Use **bold** for key metrics or amounts.
    4. Do NOT use '#' for headers (FPDF doesn't render them big). Instead, just capitalize and bold them.
    5. Keep paragraphs concise.
    6. Ensure the tone is persuasive and professional.

    SECTIONS TO INCLUDE:
    1. EXECUTIVE SUMMARY
    2. PROJECT BACKGROUND
    3. OBJECTIVES
    4. METHODOLOGY
    5. BUDGET OVERVIEW
    6. EXPECTED OUTCOMES

    FEASIBILITY REPORT:
    {content[:15000]} 
    """

    # 3. Call Gemini
    model_name = find_best_model() or "models/gemini-1.5-flash"
    url = f"https://generativelanguage.googleapis.com/v1beta/{model_name}:generateContent?key={API_KEY}"
    
    try:
        resp = requests.post(
            url, 
            headers={"Content-Type": "application/json"}, 
            json={"contents": [{"parts": [{"text": prompt}]}]}, 
            timeout=60
        )
        if resp.status_code != 200:
             raise Exception(f"Gemini Error {resp.status_code}: {resp.text}")
        
        proposal_text = resp.json()["candidates"][0]["content"]["parts"][0]["text"]
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"AI Generation Failed: {str(e)}")

    # 4. Generate PDF
    try:
        pdf_bytes = generate_pdf_from_text(proposal_text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF Generation Error: {str(e)}")

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=funding_proposal.pdf"}
    )

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=int(os.environ.get("PORT", 8000)))