import os
import requests
import uvicorn
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import Response
from fpdf import FPDF
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

app = FastAPI(title="Gemini Funding Proposal Generator")

API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    raise ValueError("GEMINI_API_KEY is missing in environment variables")

# --- PDF CLASS ---
class ProposalPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100) # Gray
        self.cell(0, 10, "Generated by AI Funding Assistant", align="R")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_pdf_from_text(text_content: str) -> bytes:
    pdf = ProposalPDF()
    pdf.add_page()
    
    # 1. Main Title (Manual PDF Title, separate from AI content)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 20, "Funding Proposal", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 2. Configure Markdown Rendering
    pdf.set_font("Times", size=12)
    safe_text = text_content.encode('latin-1', 'replace').decode('latin-1')
    
    # Render content
    pdf.multi_cell(0, 8, text=safe_text, markdown=True)
    return pdf.output()

# --- MODEL FINDER ---
def find_best_model():
    list_url = f"https://generativelanguage.googleapis.com/v1beta/models?key={API_KEY}"
    try:
        response = requests.get(list_url, timeout=10)
        if response.status_code != 200: return None
        data = response.json()
        usable = [m['name'] for m in data.get('models', []) if 'generateContent' in m.get('supportedGenerationMethods', [])]
        
        for m in usable: 
            if "flash" in m: return m
        for m in usable: 
            if "1.5-pro" in m: return m
        return usable[0] if usable else None
    except:
        return None

# --- MAIN ENDPOINT ---
@app.post("/generate-proposal/")
def generate_proposal(report_text: str = None, file: UploadFile = File(None)):
    
    # 1. Extract Content
    content = ""
    try:
        if file:
            content = file.file.read().decode("utf-8")
        elif report_text:
            content = report_text
        else:
            raise HTTPException(status_code=400, detail="Provide text or file.")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Read Error: {str(e)}")

    # 2. Strict Prompting
    prompt = f"""
    You are a professional grant writer. 
    Rewrite the provided feasibility report into a formal Funding Proposal.

    STRICT OUTPUT RULES (CRITICAL):
    1. Output ONLY the proposal content. 
    2. Do NOT include introductory filler (e.g., "Here is the proposal", "Sure", "I have rewritten...").
    3. Start your response IMMEDIATELY with the first section header (e.g., "**1. EXECUTIVE SUMMARY**").
    4. Do not add a concluding "I hope this helps" message.

    FORMATTING RULES:
    - Use Markdown.
    - Use **bold** for Section Headers.
    - Use **bold** for key numbers.
    - No '#' hashtags for headers.

    SECTIONS:
    1. EXECUTIVE SUMMARY
    2. PROJECT BACKGROUND
    3. OBJECTIVES
    4. METHODOLOGY
    5. BUDGET OVERVIEW
    6. EXPECTED OUTCOMES

    FEASIBILITY REPORT:
    {content[:15000]} 
    """

    # 3. Call AI
    model_name = find_best_model() or "models/gemini-1.5-flash"
    url = f"https://generativelanguage.googleapis.com/v1beta/{model_name}:generateContent?key={API_KEY}"
    
    try:
        resp = requests.post(
            url, 
            headers={"Content-Type": "application/json"}, 
            json={"contents": [{"parts": [{"text": prompt}]}]}, 
            timeout=60
        )
        if resp.status_code != 200:
             raise Exception(f"Gemini Error {resp.status_code}: {resp.text}")
        
        proposal_text = resp.json()["candidates"][0]["content"]["parts"][0]["text"]
        
        # CLEANUP: Remove any leading/trailing whitespace that might look like gaps
        proposal_text = proposal_text.strip()

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"AI Error: {str(e)}")

    # 4. Generate PDF
    try:
        pdf_bytes = generate_pdf_from_text(proposal_text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF Error: {str(e)}")

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=funding_proposal.pdf"}
    )

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=int(os.environ.get("PORT", 8000)))