import os
import requests
import uvicorn
import time
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import Response
from fpdf import FPDF
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

app = FastAPI(title="Gemini Funding Proposal Generator")

API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    raise ValueError("GEMINI_API_KEY is missing in environment variables")

# --- PDF CLASS ---
class ProposalPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)  # Gray
        self.cell(0, 10, "Generated by AI Funding Assistant", align="R")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_pdf_from_text(text_content: str) -> bytes:
    pdf = ProposalPDF()
    pdf.add_page()

    # 1. Main Title
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 20, "Funding Proposal", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 2. Configure Markdown Rendering
    pdf.set_font("Times", size=12)
    safe_text = text_content.encode('latin-1', 'replace').decode('latin-1')

    # Render content
    pdf.multi_cell(0, 8, text=safe_text, markdown=True)
    return pdf.output()

# --- IMPROVED MODEL FINDER: STRICTLY PRIORITIZES GEMINI-2.5-FLASH-LITE ---
def find_best_model():
    """
    Dynamically discovers available models and prioritizes gemini-2.5-flash-lite first.
    """
    list_url = f"https://generativelanguage.googleapis.com/v1beta/models?key={API_KEY}"
    print("--- Discovery: Finding available models... ---")

    try:
        response = requests.get(list_url, timeout=10)
        if response.status_code != 200:
            print("Discovery failed, falling back to gemini-2.5-flash-lite")
            return "models/gemini-2.5-flash-lite"

        data = response.json()
        all_models = data.get('models', [])
        usable_models = [
            m['name'] for m in all_models
            if 'generateContent' in m.get('supportedGenerationMethods', [])
        ]

        print(f"Found {len(usable_models)} usable models.")

        # Priority order (as of December 2025):
        # 1. gemini-2.5-flash-lite (stable, cost-efficient, low latency)
        for m in usable_models:
            if "flash-lite" in m.lower():
                print(f"Selected lite model: {m}")
                return m

        # 2. Standard gemini-2.5-flash
        for m in usable_models:
            if "2.5-flash" in m and "lite" not in m.lower():
                print(f"Selected standard flash: {m}")
                return m

        # 3. Any older flash-lite
        for m in usable_models:
            if "flash-lite" in m.lower():
                return m

        # 4. Fallback to any 1.5-flash or pro
        for m in usable_models:
            if "flash" in m or "pro" in m:
                return m

        # Final fallback
        return usable_models[0] if usable_models else "models/gemini-2.5-flash-lite"

    except Exception as e:
        print(f"Discovery Error: {e}")
        return "models/gemini-2.5-flash-lite"

# --- MAIN ENDPOINT ---
@app.post("/generate-proposal/")
def generate_proposal(report_text: str = None, file: UploadFile = File(None)):
    # 1. Extract Content
    content = ""
    try:
        if file:
            content = file.file.read().decode("utf-8")
        elif report_text:
            content = report_text
        else:
            raise HTTPException(status_code=400, detail="Provide text or file.")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Read Error: {str(e)}")

    # 2. Strict Prompting
    prompt = f"""
    You are a professional grant writer.
    Rewrite the provided feasibility report into a formal Funding Proposal.
    STRICT OUTPUT RULES (CRITICAL):
    1. Output ONLY the proposal content.
    2. Do NOT include introductory filler (e.g., "Here is the proposal").
    3. Start your response IMMEDIATELY with the first section header (e.g., "**1. EXECUTIVE SUMMARY**").
    FORMATTING RULES:
    - Use Markdown.
    - Use **bold** for Section Headers.
    - Use **bold** for key numbers.
    - No '#' hashtags for headers.
    SECTIONS:
    1. EXECUTIVE SUMMARY
    2. PROJECT BACKGROUND
    3. OBJECTIVES
    4. METHODOLOGY
    5. BUDGET OVERVIEW
    6. EXPECTED OUTCOMES
    FEASIBILITY REPORT:
    {content[:20000]}
    """

    # 3. Select Model
    model_name = find_best_model()
    print(f"--- SELECTED MODEL: {model_name} ---")

    url = f"https://generativelanguage.googleapis.com/v1beta/{model_name}:generateContent?key={API_KEY}"

    # 4. Call AI with Retry Logic for 503 Overload
    proposal_text = ""
    max_retries = 6
    for attempt in range(max_retries):
        try:
            resp = requests.post(
                url,
                headers={"Content-Type": "application/json"},
                json={"contents": [{"parts": [{"text": prompt}]}]},
                timeout=120  # Increased timeout for potentially slower lite model
            )

            if resp.status_code == 503:
                print(f"Attempt {attempt + 1}: Model overloaded (503). Retrying in {2 ** attempt} seconds...")
                if attempt < max_retries - 1:
                    time.sleep(2 ** attempt)  # Exponential backoff: 1s, 2s, 4s, 8s, 16s
                    continue
                else:
                    raise Exception("Max retries exceeded: Model remains overloaded.")

            if resp.status_code != 200:
                raise Exception(f"Gemini Error {resp.status_code}: {resp.text}")

            data = resp.json()
            proposal_text = data["candidates"][0]["content"]["parts"][0]["text"]
            proposal_text = proposal_text.strip()
            break  # Success

        except Exception as e:
            if attempt == max_retries - 1:
                raise HTTPException(status_code=500, detail=f"AI Error after retries: {str(e)}")
            time.sleep(2 ** attempt)

    # 5. Generate PDF
    try:
        pdf_bytes = generate_pdf_from_text(proposal_text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF Error: {str(e)}")

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=funding_proposal.pdf"}
    )

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=int(os.environ.get("PORT", 8000)), reload=True)
